export interface PracticalTopic {
  praNo: number;
  title: string;
  category: "FOUNDATION" | "MANEUVERS" | "ROADCRAFT" | "ASSESSMENT" | "TECHNICAL";
  phase: "PHASE 1: BASIC CONTROLS" | "PHASE 2: ROAD DYNAMICS & ASSESSMENTS" | "PHASE 3: ADVANCED DRILLS & NTSA EXAM";
  description: string;
  keySkills: string[];
  ntsaTips: string;
  estimatedMinutes: number;
}

export const OFFICIAL_PRACTICAL_TOPICS: PracticalTopic[] = [
  {
    praNo: 1,
    title: "INTRODUCTION",
    category: "FOUNDATION",
    phase: "PHASE 1: BASIC CONTROLS",
    description: "Orientation to the training vehicle, cockpit drill (DSSSM: Doors, Seat, Steering, Seatbelt, Mirrors), instrument cluster, and primary controls.",
    keySkills: [
      "Cockpit drill & ergonomic adjustment",
      "5-point safety check",
      "Identification of accelerator, brake, clutch & handbrake",
      "Ignition key stages & engine start sequence",
    ],
    ntsaTips: "Always check blind spots before opening doors and ensure all passengers buckle up.",
    estimatedMinutes: 60,
  },
  {
    praNo: 2,
    title: "USE OF BREAK,CLUTCH& HANDBRAKE",
    category: "FOUNDATION",
    phase: "PHASE 1: BASIC CONTROLS",
    description: "Mastering foot pedals coordination: finding the clutch biting point, progressive braking, and secure handbrake parking release.",
    keySkills: [
      "Finding clutch biting point without stalling",
      "Smooth moving off on flat terrain",
      "Progressive emergency and normal braking",
      "Handbrake ratchet release with button control",
    ],
    ntsaTips: "Never ride the clutch or drop it abruptly. Keep heel on the floor for progressive braking.",
    estimatedMinutes: 90,
  },
  {
    praNo: 3,
    title: "CHANGING GEARS",
    category: "FOUNDATION",
    phase: "PHASE 1: BASIC CONTROLS",
    description: "Gear lever positioning, upward and downward gear shifting (1st through 5th + Reverse), matching engine sound/RPM to gear ratio.",
    keySkills: [
      "Palming method for gear lever movement",
      "Selecting 1st gear from stationary position",
      "Smooth upshifts (1 -> 2 -> 3 -> 4 -> 5)",
      "Downshifting and block gear changes for stopping",
    ],
    ntsaTips: "Do not look down at the gear lever while driving. Keep eyes fixed on the roadway ahead.",
    estimatedMinutes: 90,
  },
  {
    praNo: 4,
    title: "STEERING CONTROL",
    category: "FOUNDATION",
    phase: "PHASE 1: BASIC CONTROLS",
    description: "Proper hand placement (10-to-2 or Quarter-to-3), pull-push steering technique, avoiding hand crossing, and straight-line tracking.",
    keySkills: [
      "Pull-push (shuffle) steering method",
      "Maintaining straight trajectory without wandering",
      "Gentle correction and self-centering of the wheel",
      "Smooth lock-to-lock transitions",
    ],
    ntsaTips: "NTSA examiners penalize crossing arms or dry steering (turning wheels while stationary).",
    estimatedMinutes: 90,
  },
  {
    praNo: 5,
    title: "ROAD POSITIONING",
    category: "ROADCRAFT",
    phase: "PHASE 1: BASIC CONTROLS",
    description: "Maintaining proper lane discipline, observing center line, road kerb clearance, and pedestrian safety margins on Kenyan roads.",
    keySkills: [
      "Driving in the center of the assigned lane",
      "Adequate clearance from kerbs, gutters, and parked cars",
      "Separation distance from cyclists and pedestrians",
      "Correct positioning on single and dual carriageways",
    ],
    ntsaTips: "Stay at least 1 meter away from parked cars to account for opening doors.",
    estimatedMinutes: 90,
  },
  {
    praNo: 6,
    title: "TURNING RIGHT &LEFT",
    category: "ROADCRAFT",
    phase: "PHASE 1: BASIC CONTROLS",
    description: "Executing precise left and right turns into major and minor roads using the MSPSL routine (Mirrors, Signal, Position, Speed, Look).",
    keySkills: [
      "Early signaling (at least 30 meters prior)",
      "Left turns: staying close to left kerb without clipping",
      "Right turns: positioning near center line without cutting corners",
      "Yielding to oncoming traffic on right turns",
    ],
    ntsaTips: "Do not cut corners into oncoming traffic lane when completing a right turn.",
    estimatedMinutes: 90,
  },
  {
    praNo: 7,
    title: "USE OF MIRRORS &HAND SIGNAL",
    category: "ROADCRAFT",
    phase: "PHASE 1: BASIC CONTROLS",
    description: "Mirror check frequency (interior rear-view, left and right wing mirrors), physical blind spot head checks, and Kenyan NTSA official hand signals.",
    keySkills: [
      "MSPSL routine execution before any maneuver",
      "Shoulder blind-spot check before moving off or changing lanes",
      "Official hand signals: I intend to turn right, turn left, and slow down/stop",
      "Mirror check before braking or signaling",
    ],
    ntsaTips: "Make deliberate head movements so the examiner clearly notes your mirror and blind spot checks.",
    estimatedMinutes: 90,
  },
  {
    praNo: 8,
    title: "REVERSING PT1",
    category: "MANEUVERS",
    phase: "PHASE 1: BASIC CONTROLS",
    description: "Basic reversing mechanics: body posture, clutch control for walking-pace speed, looking through rear window, and straight-line reverse.",
    keySkills: [
      "Reversing posture: body angled to left rear window",
      "Creeping speed via clutch feathering (under 5 km/h)",
      "Reversing in a straight line for 30 meters",
      "Frequent scanning for obstacles and children",
    ],
    ntsaTips: "Never rely purely on mirrors when reversing in a straight line; scan 360 degrees.",
    estimatedMinutes: 90,
  },
  {
    praNo: 9,
    title: "PARKING PT1(ANGLE & FLASH)",
    category: "MANEUVERS",
    phase: "PHASE 1: BASIC CONTROLS",
    description: "Angle parking (45 and 60-degree bays) and flash parking (drive-in / flush alongside kerb), clearing adjacent vehicles safely.",
    keySkills: [
      "Approach speed and turning-in pivot point",
      "Centering between angle parking bay lines",
      "Flash parking alongside kerb (parallel flush alignment)",
      "Handbrake and neutral selection upon completion",
    ],
    ntsaTips: "Do not strike the kerb or stop over the yellow bay markings.",
    estimatedMinutes: 90,
  },
  {
    praNo: 10,
    title: "DRIVING ASSESMENT 1",
    category: "ASSESSMENT",
    phase: "PHASE 2: ROAD DYNAMICS & ASSESSMENTS",
    description: "First formal instructor milestone evaluation covering basic vehicle handling, clutch control, positioning, and Phase 1 competencies.",
    keySkills: [
      "Independent cockpit drill and moving off",
      "Gear changes 1st to 3rd without stalling",
      "Basic left and right turns",
      "Emergency stop demonstration",
    ],
    ntsaTips: "Passing Assessment 1 authorizes the candidate to proceed to live urban traffic and multi-lane roadways.",
    estimatedMinutes: 90,
  },
  {
    praNo: 11,
    title: "CHANGING LANES",
    category: "ROADCRAFT",
    phase: "PHASE 2: ROAD DYNAMICS & ASSESSMENTS",
    description: "Multi-lane roadway dynamics: mirror check, blind spot check, signaling, merging with traffic speed, and safe following distances.",
    keySkills: [
      "Evaluating speed and distance of trailing traffic",
      "Mirror-Signal-Maneuver lane transition",
      "2-second following rule adherence",
      "Cancelling indicator after lane change completion",
    ],
    ntsaTips: "Always check your blind spot over the shoulder before crossing into another lane.",
    estimatedMinutes: 90,
  },
  {
    praNo: 12,
    title: "ACCELERATION &OVERTAKING",
    category: "ROADCRAFT",
    phase: "PHASE 2: ROAD DYNAMICS & ASSESSMENTS",
    description: "Safe overtaking protocols on single-lane roads: sightlines, speed difference, returning to lane without cutting off, and aborting unsafe passes.",
    keySkills: [
      "Assessing oncoming traffic distance and speed",
      "Dropping a gear for quick acceleration",
      "Overtaking stationary vs moving hazards",
      "No-overtaking zones: continuous white line, bridges, pedestrian crossings, corners",
    ],
    ntsaTips: "Never cross a solid single or double yellow/white center line to overtake.",
    estimatedMinutes: 90,
  },
  {
    praNo: 13,
    title: "ROUNDABOUTS",
    category: "ROADCRAFT",
    phase: "PHASE 2: ROAD DYNAMICS & ASSESSMENTS",
    description: "Negotiating standard and multi-lane roundabouts: lane selection according to exit, yielding right-of-way to traffic on the right, and exit signaling.",
    keySkills: [
      "Lane selection before entry (Inner vs Outer lane)",
      "Yielding to traffic circulating from the right",
      "Maintaining lane discipline inside roundabout",
      "Left signaling when approaching chosen exit",
    ],
    ntsaTips: "Golden Rule: Give way to all traffic already inside the roundabout from your right.",
    estimatedMinutes: 90,
  },
  {
    praNo: 14,
    title: "U TURN",
    category: "MANEUVERS",
    phase: "PHASE 2: ROAD DYNAMICS & ASSESSMENTS",
    description: "Executing safe U-turns at designated median breaks and wide junctions: assessing gap in oncoming traffic, full lock steering, and recovery.",
    keySkills: [
      "Selecting legal and safe U-turn spots (no 'No U-Turn' sign)",
      "Positioning in extreme right lane",
      "Full steering lock with controlled clutch roll",
      "Accelerating smoothly into lane without impeding traffic",
    ],
    ntsaTips: "Never perform a U-turn near crests of hills, sharp bends, or where prohibited by road signs.",
    estimatedMinutes: 90,
  },
  {
    praNo: 15,
    title: "REVERSING PT 2",
    category: "MANEUVERS",
    phase: "PHASE 2: ROAD DYNAMICS & ASSESSMENTS",
    description: "Advanced reversing: reversing around a left corner/kerb (reversing into a side road), maintaining constant 30cm clearance from the kerb.",
    keySkills: [
      "Approaching side road and stopping 2 car lengths past",
      "Full 360-degree observation before moving",
      "Following kerb curvature smoothly without swinging wide into road",
      "Straightening up and stopping parallel to kerb",
    ],
    ntsaTips: "If a vehicle approaches from behind or from the side road, stop immediately and wait.",
    estimatedMinutes: 90,
  },
  {
    praNo: 16,
    title: "PARKING PT 2(ANGLE & FLASH)",
    category: "MANEUVERS",
    phase: "PHASE 2: ROAD DYNAMICS & ASSESSMENTS",
    description: "Precision 90-degree bay parking (reversing into bay) and parallel flash parking between two vehicles within 2 car lengths.",
    keySkills: [
      "90-degree reverse bay parking reference points",
      "Parallel parking: 45-degree angle reverse, counter-steering into kerb",
      "Stopping within 15-30 cm of the kerb",
      "Zero tire scrub against concrete kerbing",
    ],
    ntsaTips: "Parallel parking is a core NTSA practical test component. Mount of kerb = instant failure.",
    estimatedMinutes: 90,
  },
  {
    praNo: 17,
    title: "THEORY BOARD ASSESEMENT",
    category: "ASSESSMENT",
    phase: "PHASE 2: ROAD DYNAMICS & ASSESSMENTS",
    description: "Mastery of the Model Town Board (MTB): rule of the road, priority at junctions, one-way and two-way roads, roundabouts, and navigating from Point A to Point B.",
    keySkills: [
      "Model Town Board layout navigation",
      "Four lane roundabout rules on board",
      "Regulatory, warning, and informative road signs identification",
      "Answering oral questions on right-of-way and vehicle mechanics",
    ],
    ntsaTips: "You must pass the Model Town Board oral exam before you are allowed into the NTSA driving vehicle.",
    estimatedMinutes: 90,
  },
  {
    praNo: 18,
    title: "DRIVING ASSSESEMENT 2",
    category: "ASSESSMENT",
    phase: "PHASE 2: ROAD DYNAMICS & ASSESSMENTS",
    description: "Mid-training comprehensive practical road assessment: urban driving, roundabouts, speed control, pedestrian crossings, and confidence evaluation.",
    keySkills: [
      "Independent driving on public highways without instructor verbal prompt",
      "Hazard perception and anticipation",
      "Smooth gear downshifts and hill management",
      "Overall road etiquette and calmness",
    ],
    ntsaTips: "Demonstrates test readiness for Phase 3 advanced drills and government booking.",
    estimatedMinutes: 90,
  },
  {
    praNo: 19,
    title: "BASIC MECHANICAL",
    category: "TECHNICAL",
    phase: "PHASE 3: ADVANCED DRILLS & NTSA EXAM",
    description: "Under-the-bonnet engine inspection: engine oil dipstick, coolant level, brake fluid reservoir, battery terminals, tire pressure, and changing a flat tire.",
    keySkills: [
      "Checking engine oil level & viscosity",
      "Brake fluid and power steering fluid reservoirs check",
      "Fan belt tension and battery corrosion check",
      "Jack positioning, lug wrench operation, and spare tire replacement",
    ],
    ntsaTips: "Examiners frequently ask candidates to identify fluid reservoirs and state their recommended levels.",
    estimatedMinutes: 90,
  },
  {
    praNo: 20,
    title: "JUNCTION DRILL",
    category: "ROADCRAFT",
    phase: "PHASE 3: ADVANCED DRILLS & NTSA EXAM",
    description: "Mastering complex Kenyan urban junctions: T-junctions, staggered junctions, crossroads, yellow box junctions, and traffic light sequences.",
    keySkills: [
      "Creep and peep technique at blind junctions",
      "Yellow box junction rule (enter only if exit is clear)",
      "Traffic light phases & filter arrows",
      "Right turn priority vs oncoming traffic",
    ],
    ntsaTips: "Never enter a yellow box junction unless your exit road or lane is completely clear.",
    estimatedMinutes: 90,
  },
  {
    praNo: 21,
    title: "THREE POINT TURN",
    category: "MANEUVERS",
    phase: "PHASE 3: ADVANCED DRILLS & NTSA EXAM",
    description: "Turning the car around in a narrow road (Turn in the Road): forward across, reverse across, and drive forward, without touching the kerbs.",
    keySkills: [
      "Full observation before each leg of the turn",
      "Move forward with right lock, stop 1 foot before kerb",
      "Reverse with left lock, scan both directions, stop before rear kerb",
      "Move forward with right lock into the new lane",
    ],
    ntsaTips: "Keep vehicle speed at walking pace using clutch bite; do not bump or mount either kerb.",
    estimatedMinutes: 90,
  },
  {
    praNo: 22,
    title: "EXAMINATION EVALUATION TEST",
    category: "ASSESSMENT",
    phase: "PHASE 3: ADVANCED DRILLS & NTSA EXAM",
    description: "Full mock NTSA driving test conducted under strict examination conditions: Model Town Board oral test, pre-drive check, driving test, and parking test.",
    keySkills: [
      "Simulated NTSA practical test route",
      "Scoring sheet simulation (minor and major faults)",
      "Stress management under examiner scrutiny",
      "Immediate feedback review and remediation",
    ],
    ntsaTips: "Treat the mock test as the real government examination. Any major fault = retake drill.",
    estimatedMinutes: 120,
  },
  {
    praNo: 23,
    title: "HILL START",
    category: "MANEUVERS",
    phase: "PHASE 3: ADVANCED DRILLS & NTSA EXAM",
    description: "Stopping and moving off on steep gradients: handbrake engagement, setting engine revs, finding biting point, and moving off with zero roll-back.",
    keySkills: [
      "Stopping on steep gradient with handbrake secure",
      "Rev-setting (1500–2000 RPM) + clutch bite until bonnet raises slightly",
      "Smooth handbrake release with no roll-back",
      "Downhill start protocols (reverse gear or 1st gear)",
    ],
    ntsaTips: "Even 1 inch of backward roll during NTSA hill test is penalized heavily. Practice until instinctive.",
    estimatedMinutes: 90,
  },
  {
    praNo: 24,
    title: "PARKING PT 3(ANGLE & FLASH)",
    category: "MANEUVERS",
    phase: "PHASE 3: ADVANCED DRILLS & NTSA EXAM",
    description: "Mastery and speed refinement of tight angle parking and high-pressure parallel flash parking in busy commercial areas and test centers.",
    keySkills: [
      "Confined space parking between closely spaced vehicles",
      "Reversing into angle bay at speed with precision",
      "Mirror-only alignment checks",
      "Final lock check and safety securing",
    ],
    ntsaTips: "Take your time, use reference points, and adjust calmly if alignment is off.",
    estimatedMinutes: 90,
  },
  {
    praNo: 25,
    title: "REVERSING PT 3",
    category: "MANEUVERS",
    phase: "PHASE 3: ADVANCED DRILLS & NTSA EXAM",
    description: "Final comprehensive reversing mastery: complex S-curves, tight alleyways, reverse incline maneuvers, and final certification sign-off.",
    keySkills: [
      "Reversing along curved pathways and obstructions",
      "Reverse hill control with clutch feathering",
      "Final sign-off by Chief Instructor / Official signature",
      "Official certificate readiness for NTSA test date booking",
    ],
    ntsaTips: "Congratulations! Completion of Lesson 25 certifies the candidate for the National Driving License Test.",
    estimatedMinutes: 90,
  },
];
